version: '3.8'

services:
  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=test
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=photos
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - minio

  api-service:
    container_name: api-minio
    build: .
    depends_on:
      minio:
        condition: service_started
    ports:
      - "50040:50040"
    networks:
      - minio

volumes:
  minio_data:
    driver: local
networks:
  minio:
    driver: bridge